language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

osx_image: xcode10.1

xcode_sdk: iphonesimulator12.1

script:
  - set -o pipefail
  - xcodebuild -showsdks
  - xcodebuild -project Commercetools.xcodeproj -scheme "Commercetools iOS" -destination "platform=iOS Simulator,name=iPhone 6" test | xcpretty -c;