language: objective-c

before_install:
  - gem install xcpretty --no-document --quiet

osx_image: xcode10.2

xcode_sdk: iphonesimulator12.2

script:
  - set -o pipefail
  - xcodebuild -showsdks
  - xcodebuild -project Commercetools.xcodeproj -scheme "Commercetools iOS" -destination "platform=iOS Simulator,name=iPhone 6" test | xcpretty -c;