language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

install:
   - pod repo update
   - pod install

osx_image: xcode8.3

xcode_sdk: iphonesimulator10.0

script:
  - set -o pipefail
  - xcodebuild -showsdks
  - xcodebuild -workspace Commercetools.xcworkspace -scheme "Commercetools iOS" -destination "platform=iOS Simulator,name=iPhone 6" test | xcpretty -c;

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true
